import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { useDispatch } from "react-redux";
import { useSelector } from "react-redux";
import { chooseTopic, chooseAmmount } from "../redux/quizSlice";
import { getTopic, getAmmount } from "../redux/selectors";
import Link from "next/link";

export default function Home() {
    const dispatch = useDispatch();
    const Topic = useSelector(getTopic);
    const Ammount = useSelector(getAmmount);


    const selectTopic = (e) => {
        console.log(e.target.id);
        dispatch(chooseTopic(e.target.id));
    };

    const selectAmmount = (e) => {
        console.log(e.target.id);
        dispatch(chooseAmmount(e.target.id));
    };

    if (Topic !== "" && Ammount !== 0) {
        return ( <
            main className = { styles.main } >
            <
            h2 > Loading... / < /h2> < /
            main >
        );
    } else {
        return ( <
                >
                <
                Head >
                <
                meta name = "description"
                content = "Generated by create next app" / >
                <
                meta name = "viewport"
                content = "width=device-width, initial-scale=1" / >
                <
                link rel = "icon"
                href = "/favicon.ico" / >
                <
                /Head>{" "} <
                main className = { styles.main } >
                <
                div className = { styles.description } >
                <
                p > Choose your quiz: < /p>{" "} {
                Topic === "" ? ( <
                    ul className = { styles.topic_list } >
                    <
                    li className = { styles.topic_li } >
                    <
                    button id = "Movies"
                    onClick = { selectTopic }
                    type = "button" >
                    Movies { " " } <
                    /button>{" "} < /
                    li > { " " } <
                    li className = { styles.topic_li }
                    onClick = { selectTopic } >
                    <
                    button type = "button"
                    id = "Science&Nature" > { " " }
                    Science & Nature { " " } <
                    /button>{" "} < /
                    li > { " " } <
                    li className = { styles.topic_li }
                    onClick = { selectTopic } >
                    <
                    button type = "button"
                    id = "Geography" > { " " }
                    Geography { " " } <
                    /button>{" "} < /
                    li > { " " } <
                    /ul>
                ) : ( <
                    ul className = { styles.topic_list } >
                    <
                    li className = { styles.topic_li } >
                    <
                    Link onClick = { selectAmmount }
                    href = {
                        {
                            pathname: "/quiz",
                            query: {
                                topic: Topic,
                                ammount: 10,
                            },
                        }
                    } > { " " } <
                    button id = "10"
                    type = "button" >
                    10 { " " } <
                    /button>{" "} < /
                    Link > { " " } <
                    /li>{" "} <
                    li className = { styles.topic_li } >
                    <
                    Link onClick = { selectAmmount }
                    href = {
                        {
                            pathname: "/quiz",
                            query: {
                                topic: Topic,
                                ammount: 15,
                            },
                        }
                    } >
                    <
                    button type = "button"
                    id = "15" >
                    15 { " " } <
                    /button>{" "} < /
                    Link > { " " } <
                    /li>{" "} <
                    li className = { styles.topic_li } >
                    <
                    Link onClick = { selectAmmount }
                    href = {
                        {
                            pathname: "/quiz",
                            query: {
                                topic: Topic,
                                ammount: 20,
                            },
                        }
                    } >
                    <
                    button type = "button"
                    id = "20" >
                    20 { " " } <
                    /button>{" "} < /
                    Link > { " " } <
                    /li>{" "} < /
                    ul >
                )
            } { " " } <
            /div>{" "} < /
        main > { " " } <
            />
    );
}
}

/*
quiz={quiz}

*/