import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetStaticProps } from "next";
import { Question } from "../pages/components/question";
import { message } from "antd";
import { useState } from "react";
import { ScoreTable } from "./components/ScoreTable";
import { Quiz } from "../pages/quiz";
import Link from "next/link";

/*
make few quizes
add redux
add styles
add question ammount choose
*/

export default function Home({ quiz }) {
    const [topic, setTopic] = useState("");

    const chooseTopic = (e) => {
        console.log(e.target.id);
        setTopic(e.target.id);
    };

    console.log(topic);

    return ( <
            >
            <
            Head >
            <
            meta name = "description"
            content = "Generated by create next app" / >
            <
            meta name = "viewport"
            content = "width=device-width, initial-scale=1" / >
            <
            link rel = "icon"
            href = "/favicon.ico" / >
            <
            /Head>{" "} <
            main className = { styles.main } >
            <
            div className = { styles.description } >
            <
            p > Choose your quiz: < /p>{" "} {
            topic === "" ? ( <
                ul className = { styles.topic_list } >
                <
                li className = { styles.topic_li } >
                <
                button id = "Movies"
                onClick = { chooseTopic }
                type = "button" >
                Movies { " " } <
                /button>{" "} < /
                li > { " " } <
                li className = { styles.topic_li }
                onClick = { chooseTopic } >
                <
                button type = "button"
                id = 'Science&Nature' > Science & Nature < /button>{" "} < /
                li > { " " } <
                li className = { styles.topic_li }
                onClick = { chooseTopic } >
                <
                button type = "button"
                id = 'Geography' > Geography < /button>{" "} < /
                li > { " " } <
                /ul>
            ) : ( <
                ul className = { styles.topic_list } >
                <
                li className = { styles.topic_li } >
                <
                Link href = {
                    {
                        pathname: "/quiz",
                        query: {
                            topic: topic,
                            ammount: 10,
                        },
                    }
                } > { " " } <
                button id = "10"
                type = "button" >
                10 { " " } <
                /button>{" "} < /
                Link > { " " } <
                /li> <
                li className = { styles.topic_li } >
                <
                Link href = {
                    {
                        pathname: "/quiz",
                        query: {
                            topic: topic,
                            ammount: 15,
                        },
                    }
                } >
                <
                button type = "button"
                id = "15" >
                15 { " " } <
                /button>{" "} < /
                Link > { " " } <
                /li> <
                li className = { styles.topic_li } >
                <
                Link href = {
                    {
                        pathname: "/quiz",
                        query: {
                            topic: topic,
                            ammount: 20,
                        },
                    }
                } >
                <
                button type = "button"
                id = "20" >
                20 { " " } <
                /button>{" "} < /
                Link > { " " } <
                /li>{" "} < /
                ul >
            )
        } { " " } <
        /div>{" "} < /
        main > { " " } <
        />
);
}

/*
quiz={quiz}

*/